name: zposter38

dependencies:
  - python=3.8
  - pip >=21.1
  - pip:
    - matplotlib
    - pandas
    - scipy
    - zfit
    - mplhep
    - pygit2
    - jupyter-sphinx
    - myst-nb
    - mdit-py-plugins  # temporary fix
    - Sphinx >= 3,<4
    - sphinx-book-theme
    - sphinx-panels
    - sphinx-thebe
    - sphinx-togglebutton
    - sphinx-copybutton
