name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1



      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: zposter38
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Install dependencies
        run: |
          pip install -r website/zfit-tutorials/requirements.txt
      - name: Build
        run: |
          cd website
          make html -j4
          touch _build/html/.nojekyll
          cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/_build/html # The folder the action should deploy.
