name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          pip install -U pip
          pip install -r requirements.txt
          cd website
          make clean
          make html
          touch _build/html/.nojekyll
          cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/_build # The folder the action should deploy.
